version: "3"

services:

  webapp:
    build:
      dockerfile: WebAppDocker/Dockerfile
      context: .
    ports:
      - "8080:80"
    networks:
      - my-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
   
  ch:
    build:
      dockerfile: CT/Dockerfile
      context: .
    ports:
      - "8081:80" 
    networks:
      - my-network
    environment:
      - API_URL=Api:80
  
  hc:
    build:
      dockerfile: HT/Dockerfile
      context: .
    ports:
      - "8082:80"
    networks:
      - my-network
    environment:
      - API_URL=Api:80
        
networks:
  my-network:
    external: true